### ISSUE TITLE
Support Scala 2 refinement types (test case scala.collection.MapView.withFilter)

### ISSUE THREAD

**Issue by adpi2** [scalacenter/tasty-query#167]
```scala
  testWithContext("MapView.withFilter") {
    val MapView = resolve(RootPkg / name"scala" / name"collection" / tname"MapView").asClass
  }
```

The full stack trace is:
```
==> X tastyquery.TypeSuite.MapView.withFilter  0.008s tastyquery.Exceptions$Scala2PickleFormatException: error while unpickling the type of symbol[class MapView].withFilter
    at tastyquery.reader.pickles.PickleReader.readSymType$1(PickleReader.scala:193)
    at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbol(PickleReader.scala:239)
    at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbolAt(PickleReader.scala:113)
    at tastyquery.reader.pickles.Unpickler$.run$2(Unpickler.scala:17)
    at tastyquery.reader.pickles.Unpickler$.loadInfo$$anonfun$1(Unpickler.scala:46)
    at tastyquery.reader.pickles.PickleReader$PklStream$.read(PickleReader.scala:652)
    at tastyquery.reader.pickles.Unpickler$.loadInfo(Unpickler.scala:47)
    at tastyquery.reader.classfiles.ClassfileParser$.loadScala2Class(ClassfileParser.scala:50)
    at tastyquery.reader.Loaders$Loader.inspectClass$1(Loaders.scala:65)
    at tastyquery.reader.Loaders$Loader.completeRoot(Loaders.scala:93)
    at tastyquery.reader.Loaders$Loader.loadRoot(Loaders.scala:130)
    at tastyquery.Symbols$PackageSymbol.getDecl$$anonfun$1(Symbols.scala:731)
    at scala.Option.orElse(Option.scala:477)
    at tastyquery.Symbols$PackageSymbol.getDecl(Symbols.scala:733)
    at tastyquery.Contexts$Context.rec$2(Contexts.scala:93)
    at tastyquery.Contexts$Context.findSymbolFromRoot(Contexts.scala:97)
    at tastyquery.Paths$.resolve(Paths.scala:22)
    at tastyquery.TypeSuite.$init$$$anonfun$38(TypeSuite.scala:782)
    at tastyquery.UnrestrictedUnpicklingSuite.testWithContext$$anonfun$1(UnrestrictedUnpicklingSuite.scala:9)
    at tastyquery.UnrestrictedUnpicklingSuite.testWithContext$$anonfun$3$$anonfun$1(UnrestrictedUnpicklingSuite.scala:15)
    at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:431)
    at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
    at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
    at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.AssertionError: assertion failed: trying to add a second entry symbol[class <refinement>] for type name <refinement> in symbol[class MapView]
    at tastyquery.Symbols$ClassSymbol.addDecl(Symbols.scala:525)
    at tastyquery.Symbols$Symbol.addDeclIfDeclaringSym(Symbols.scala:139)
    at tastyquery.Symbols$ClassSymbol$.create(Symbols.scala:660)
    at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbol(PickleReader.scala:220)
    at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbolAt(PickleReader.scala:113)
    at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbolRef(PickleReader.scala:106)
    at tastyquery.reader.pickles.PickleReader.readLocalSymbolRef(PickleReader.scala:94)
    at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbol(PickleReader.scala:163)
    at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbolAt(PickleReader.scala:113)
    at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbolRef(PickleReader.scala:106)
    at tastyquery.reader.pickles.PickleReader.readLocalSymbolRef(PickleReader.scala:94)
    at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbol(PickleReader.scala:163)
    at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbolAt(PickleReader.scala:113)
    at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbolRef(PickleReader.scala:106)
    at tastyquery.reader.pickles.PickleReader.readLocalSymbolRef(PickleReader.scala:94)
    at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbol(PickleReader.scala:163)
    at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbolAt(PickleReader.scala:113)
    at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbolRef(PickleReader.scala:106)
    at tastyquery.reader.pickles.PickleReader.readType(PickleReader.scala:406)
    at tastyquery.reader.pickles.PickleReader.readTypeRef$$anonfun$1(PickleReader.scala:355)
    at tastyquery.reader.pickles.PickleReader.at(PickleReader.scala:66)
    at tastyquery.reader.pickles.PickleReader.readTypeRef(PickleReader.scala:355)
    at tastyquery.reader.pickles.PickleReader.$anonfun$4(PickleReader.scala:431)
    at tastyquery.reader.pickles.PickleBuffer.until(PickleBuffer.scala:76)
    at tastyquery.reader.pickles.PickleReader$PklStream.until(PickleReader.scala:660)
    at tastyquery.reader.pickles.PickleReader.readType(PickleReader.scala:431)
    at tastyquery.reader.pickles.PickleReader.readTypeRef$$anonfun$1(PickleReader.scala:355)
    at tastyquery.reader.pickles.PickleReader.at(PickleReader.scala:66)
    at tastyquery.reader.pickles.PickleReader.readTypeRef(PickleReader.scala:355)
    at tastyquery.reader.pickles.PickleReader.$anonfun$4(PickleReader.scala:431)
    at tastyquery.reader.pickles.PickleBuffer.until(PickleBuffer.scala:76)
    at tastyquery.reader.pickles.PickleReader$PklStream.until(PickleReader.scala:660)
    at tastyquery.reader.pickles.PickleReader.readType(PickleReader.scala:431)
    at tastyquery.reader.pickles.PickleReader.readTypeRef$$anonfun$1(PickleReader.scala:355)
    at tastyquery.reader.pickles.PickleReader.at(PickleReader.scala:66)
    at tastyquery.reader.pickles.PickleReader.readTypeRef(PickleReader.scala:355)
    at tastyquery.reader.pickles.PickleReader.readType(PickleReader.scala:484)
    at tastyquery.reader.pickles.PickleReader.readTypeRef$$anonfun$1(PickleReader.scala:355)
    at tastyquery.reader.pickles.PickleReader.at(PickleReader.scala:66)
    at tastyquery.reader.pickles.PickleReader.readTypeRef(PickleReader.scala:355)
    at tastyquery.reader.pickles.PickleReader.$anonfun$4(PickleReader.scala:431)
    at tastyquery.reader.pickles.PickleBuffer.until(PickleBuffer.scala:76)
    at tastyquery.reader.pickles.PickleBuffer.until(PickleBuffer.scala:76)
    at tastyquery.reader.pickles.PickleBuffer.until(PickleBuffer.scala:76)
    at tastyquery.reader.pickles.PickleBuffer.until(PickleBuffer.scala:76)
    at tastyquery.reader.pickles.PickleReader$PklStream.until(PickleReader.scala:660)
    at tastyquery.reader.pickles.PickleReader.readType(PickleReader.scala:431)
    at tastyquery.reader.pickles.PickleReader.readTypeRef$$anonfun$1(PickleReader.scala:355)
    at tastyquery.reader.pickles.PickleReader.at(PickleReader.scala:66)
    at tastyquery.reader.pickles.PickleReader.readTypeRef(PickleReader.scala:355)
    at tastyquery.reader.pickles.PickleReader.readType(PickleReader.scala:467)
    at tastyquery.reader.pickles.PickleReader.readSymType$2$$anonfun$1(PickleReader.scala:190)
    at tastyquery.reader.pickles.PickleReader.at(PickleReader.scala:66)
    at tastyquery.reader.pickles.PickleReader.readSymType$1(PickleReader.scala:190)
```

**Comment by adpi2** [comment]
At least it should not crash when reading a Scala 2 refinement type.
