### ISSUE TITLE
Unexpected type tag TYPEBOUNDS at address Addr(298)

### ISSUE THREAD

**Issue by adpi2** [scalacenter/tasty-query#356]
```scala
package example

class A {
  def m(x: Int): String ?=> String = ???
  def m(): (Int, String) ?=> Int = ???
  def m(x: String): Int ?=> String ?=> String = ???
  def mbis: ? ?=> String = ???
}
```

```
tastyquery.Exceptions$TastyFormatException: Unexpected type tag TYPEBOUNDS at address Addr(298) in file /tmp/scala-debug-adapter7599745288498851691/classes/example/A.tasty
    at tastyquery.reader.tasties.TreeUnpickler.readTypeMappable(TreeUnpickler.scala:1335)
    at tastyquery.reader.tasties.TreeUnpickler.readNonEmptyPrefix(TreeUnpickler.scala:1165)
    at tastyquery.reader.tasties.TreeUnpickler.doReadTypeTree(TreeUnpickler.scala:1595)
    at tastyquery.reader.tasties.TreeUnpickler.readTypeTree(TreeUnpickler.scala:1481)
    at tastyquery.reader.tasties.TreeUnpickler.doReadValOrDefDef(TreeUnpickler.scala:736)
    at tastyquery.reader.tasties.TreeUnpickler.readValOrDefDef(TreeUnpickler.scala:725)
    at tastyquery.reader.tasties.TreeUnpickler.readParams(TreeUnpickler.scala:706)
    at tastyquery.reader.tasties.TreeUnpickler.readAllParams(TreeUnpickler.scala:689)
    at tastyquery.reader.tasties.TreeUnpickler.doReadValOrDefDef(TreeUnpickler.scala:735)
    at tastyquery.reader.tasties.TreeUnpickler.readValOrDefDef(TreeUnpickler.scala:725)
    at tastyquery.reader.tasties.TreeUnpickler.doReadStat(TreeUnpickler.scala:504)
    at tastyquery.reader.tasties.TreeUnpickler.readStat(TreeUnpickler.scala:449)
    at tastyquery.reader.tasties.TreeUnpickler.readStats$$anonfun$1(TreeUnpickler.scala:446)
    at dotty.tools.tasty.TastyReader.until(TastyReader.scala:125)
    at tastyquery.reader.tasties.TreeUnpickler.readStats(TreeUnpickler.scala:446)
    at tastyquery.reader.tasties.TreeUnpickler.doReadTerm(TreeUnpickler.scala:973)
```

**Comment by sjrd** [comment]
So this one is really a dotc issue: https://github.com/lampepfl/dotty/issues/18649

**Comment by bishabosha** [comment]
Shouldn't we handle it anyway? seems like dotty doesnt crash

**Comment by bishabosha** [comment]
If I compile `A` first, and then read it from the classpath, this is the error for calling `mbis`:
```scala
object Test:
  def test =
    val a = example.A()
    given String = "abc"
    given Int = 1
    a.m(23)
    a.m()
    a.m("abc")
    a.mbis
```
error:
```scala
Compiling project (Scala 3.3.1, JVM)
[error] ./bar.scala:9:11
[error] No given instance of type ?1.scala$ContextFunction1$$T1 was found for parameter of (?) ?=> String
[error] 
[error] where:    ?1 is an unknown value of type (?) ?=> String
[error]     a.mbis
[error]           ^
Error compiling project (Scala 3.3.1, JVM)
```

**Comment by sjrd** [comment]
No I really don't think we can or want to handle this. It's fundamentally invalid. It's like declaring a `val x: ? = ...`. That makes no sense.

**Comment by sjrd** [comment]
The issue was fixed upstream.
