### ISSUE TITLE
Error while unpickling the type of `symbol[class Console].outVar`

### ISSUE THREAD

**Issue by adpi2** [scalacenter/tasty-query#78]
In  `scala.Console` the type of `outVar` cannot be unpickled:

```
2022.09.06 10:49:47 ERROR java.lang.IllegalStateException: error while unpickling the type of symbol[class Console].outVar
	at tastyquery.reader.pickles.PickleReader.readSymType$1(PickleReader.scala:185)
	at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbol(PickleReader.scala:205)
	at tastyquery.reader.pickles.Unpickler$.run$1(Unpickler.scala:16)
	at tastyquery.reader.pickles.Unpickler$.liftedTree1$1(Unpickler.scala:43)
	at tastyquery.reader.pickles.Unpickler$.loadInfo$$anonfun$1(Unpickler.scala:44)
	at tastyquery.reader.pickles.PickleReader$PklStream$.read(PickleReader.scala:453)
	at tastyquery.reader.pickles.Unpickler$.loadInfo(Unpickler.scala:45)
	at tastyquery.reader.classfiles.ClassfileParser$.loadScala2Class(ClassfileParser.scala:55)
	at tastyquery.reader.classfiles.Classpaths$Loader.inspectClass$1(Classpaths.scala:127)
	at tastyquery.reader.classfiles.Classpaths$Loader.completeRoots$2$$anonfun$1(Classpaths.scala:162)
	at tastyquery.reader.classfiles.Classpaths$Loader.completeRoots$1(Classpaths.scala:38)
	at tastyquery.reader.classfiles.Classpaths$Loader.scanClass(Classpaths.scala:174)
	at tastyquery.ast.Symbols$ClassSymbol.initRoot$1(Symbols.scala:358)
	at tastyquery.ast.Symbols$ClassSymbol.initialiseMembers$3$$anonfun$2(Symbols.scala:361)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.Option.foreach(Option.scala:437)
	at tastyquery.ast.Symbols$ClassSymbol.initialiseMembers$1(Symbols.scala:361)
	at tastyquery.ast.Symbols$ClassSymbol.ensureInitialised(Symbols.scala:366)
	at tastyquery.ast.Symbols$DeclaringSymbol.declarations(Symbols.scala:300)
        ...
Caused by: java.lang.ClassCastException: tastyquery.ast.Types$TermRef cannot be cast to tastyquery.ast.Types$TypeRef
	at tastyquery.reader.pickles.PickleReader$ExternalSymbolRef.toTypeRef(PickleReader.scala:487)
	at tastyquery.reader.pickles.PickleReader.readType(PickleReader.scala:281)
	at tastyquery.reader.pickles.PickleReader.readTypeRef$$anonfun$1(PickleReader.scala:254)
	at tastyquery.reader.pickles.PickleReader.at(PickleReader.scala:64)
	at tastyquery.reader.pickles.PickleReader.readTypeRef(PickleReader.scala:254)
	at tastyquery.reader.pickles.PickleReader.readPrefix(PickleReader.scala:248)
	at tastyquery.reader.pickles.PickleReader.readType(PickleReader.scala:297)
	at tastyquery.reader.pickles.PickleReader.readTypeRef$$anonfun$1(PickleReader.scala:254)
	at tastyquery.reader.pickles.PickleReader.at(PickleReader.scala:64)
	at tastyquery.reader.pickles.PickleReader.readTypeRef(PickleReader.scala:254)
	at tastyquery.reader.pickles.PickleReader.$anonfun$2(PickleReader.scala:322)
	at tastyquery.reader.pickles.PickleBuffer.until(PickleBuffer.scala:78)
	at tastyquery.reader.pickles.PickleReader$PklStream.until(PickleReader.scala:461)
	at tastyquery.reader.pickles.PickleReader.readType(PickleReader.scala:322)
	at tastyquery.reader.pickles.PickleReader.readSymType$2$$anonfun$1(PickleReader.scala:182)
	at tastyquery.reader.pickles.PickleReader.at(PickleReader.scala:64)
	at tastyquery.reader.pickles.PickleReader.readSymType$1(PickleReader.scala:182)
	at tastyquery.reader.pickles.PickleReader.readMaybeExternalSymbol(PickleReader.scala:205)
	at tastyquery.reader.pickles.Unpickler$.run$1(Unpickler.scala:16)
	at tastyquery.reader.pickles.Unpickler$.liftedTree1$1(Unpickler.scala:43)
	at tastyquery.reader.pickles.Unpickler$.loadInfo$$anonfun$1(Unpickler.scala:44)
	at tastyquery.reader.pickles.PickleReader$PklStream$.read(PickleReader.scala:453)
	at tastyquery.reader.pickles.Unpickler$.loadInfo(Unpickler.scala:45)
	at tastyquery.reader.classfiles.ClassfileParser$.loadScala2Class(ClassfileParser.scala:55)
	at tastyquery.reader.classfiles.Classpaths$Loader.inspectClass$1(Classpaths.scala:127)
	at tastyquery.reader.classfiles.Classpaths$Loader.completeRoots$2$$anonfun$1(Classpaths.scala:162)
	at tastyquery.reader.classfiles.Classpaths$Loader.completeRoots$1(Classpaths.scala:38)
	at tastyquery.reader.classfiles.Classpaths$Loader.scanClass(Classpaths.scala:174)
	at tastyquery.ast.Symbols$ClassSymbol.initRoot$1(Symbols.scala:358)
	at tastyquery.ast.Symbols$ClassSymbol.initialiseMembers$3$$anonfun$2(Symbols.scala:361)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.Option.foreach(Option.scala:437)
	at tastyquery.ast.Symbols$ClassSymbol.initialiseMembers$1(Symbols.scala:361)
	at tastyquery.ast.Symbols$ClassSymbol.ensureInitialised(Symbols.scala:366)
	at tastyquery.ast.Symbols$DeclaringSymbol.declarations(Symbols.scala:300)
	...
```

**Comment by adpi2** [comment]
Same bug with `symbol[class ScalaRunTime].ensureAccessible`
